// Auto-generated by flutterfire configure --project=flashy-647b2
// This file provides Firebase options for platforms that need explicit config.
// Android auto-discovers from google-services.json.
// iOS needs GoogleService-Info.plist.
// Web needs the values below.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEFAULT_API_KEY_FOR_WEB',
    appId: '1:123456789:web:abc123def456',
    messagingSenderId: '123456789',
    projectId: 'flashy-647b2',
    authDomain: 'flashy-647b2.firebaseapp.com',
    storageBucket: 'flashy-647b2.appspot.com',
    measurementId: 'G-MEASUREMENT_ID',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANDROID_API_KEY',
    appId: '1:123456789:android:abc123def456',
    messagingSenderId: '123456789',
    projectId: 'flashy-647b2',
    storageBucket: 'flashy-647b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyIOS_API_KEY',
    appId: '1:123456789:ios:abc123def456',
    messagingSenderId: '123456789',
    projectId: 'flashy-647b2',
    storageBucket: 'flashy-647b2.appspot.com',
    iosBundleId: 'com.example.flashy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyMACOS_API_KEY',
    appId: '1:123456789:macos:abc123def456',
    messagingSenderId: '123456789',
    projectId: 'flashy-647b2',
    storageBucket: 'flashy-647b2.appspot.com',
    iosBundleId: 'com.example.flashy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyWINDOWS_API_KEY',
    appId: '1:123456789:windows:abc123def456',
    messagingSenderId: '123456789',
    projectId: 'flashy-647b2',
    storageBucket: 'flashy-647b2.appspot.com',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyLINUX_API_KEY',
    appId: '1:123456789:linux:abc123def456',
    messagingSenderId: '123456789',
    projectId: 'flashy-647b2',
    storageBucket: 'flashy-647b2.appspot.com',
  );
}
